#!/usr/bin/env bash

# Loads the index controller

DOCUMENT_ROOT="$(realpath "$(dirname "$0")")/www"
HTTP_HOST=localhost
HTTP_REFERER=http://localhost/
HTTP_USER_AGENT='www.sh-tests/1'

QUERY_STRING='welcome=Test+Get%20User'
SCRIPT_NAME='/'
REQUEST_URI="$SCRIPT_NAME?$QUERY_STRING"

cd "$DOCUMENT_ROOT"
echo 'welcome=Test+Post%20User' | source index.cgi
